### ISSUE TITLE
vcs.scriptrun('plot_set_5.json') doesn't make a difference in output

### ISSUE THREAD

**Issue by zshaheen** [zshaheen/acme-diags#1]

**Comment by chengzhuzhang** [comment]
The extra setting for placing header, lable, etc. are in amwg5.py in customizeTemplate and extraCustomizeTemplates. We may try put all relevant csv setting in plot_set_5.json?

**Comment by chengzhuzhang** [comment]
We may also put the color bar interval to plot_set_5.json?

'PRECT': {'MODEL': {'difference': [-8, -6, -4, -3, -2, -1, -0.5, 0, 0.5, 1, 2, 3, 4, 6, 8], 'contours': [0.2, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 17]},

**Comment by chengzhuzhang** [comment]
I tried plot:
 the model data without regridding
together with:
aa1=x.createisofill()
aa1.levels=[0,0.2, 0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 17]
The model plot matches the target for max,min,mean and contours.

**Comment by zshaheen** [comment]
@chengzhuzhang you can upload your code with the changes you were talking about after your vacation. I tried your above instructions but I get an error because the shapes are different. Let me know if you need help with this. Hope you're having fun during your time off!
