### ISSUE TITLE
Support for horizontal slices of 3d variables

### ISSUE THREAD

**Issue by golaz** [zshaheen/acme-diags#10]
Need flexible support for plotting horizontal slices of 3d variables. The desired level should be specified as part of the plot specifications. Vertical re-mapping should be performed only if (1) the data is in hybrid coordinates or (2) the data is in pressure coordinate, but the desired level is not available natively.

**Comment by chengzhuzhang** [comment]
Flexible to support horizontal slice: 
1. both hybrid and pressure. Abort if neither hybrid nor pressure. (Note: search "hybrid", "pressure" or "isobaric" from long_name of level axis. It is possible that other long names being used for datasets)
2. Take non-native plev
3. plev takes from parameter file.

Note, cdutil.vertical.logLinearInterpolation has to take "positive down" level axis, also has issue dealing with missing values (MERRA reanalysis).

**Comment by zshaheen** [comment]
@chengzhuzhang One quick note, the `-v` is already used for the variables on the command line. We can change either the `plev` or `variables` to accept `-v`, but only one of them should.

**Comment by chengzhuzhang** [comment]
@zshaheen Thanks! Can I set the parameter as a number instead of a string? If so how should I change acme_parser.py?

**Comment by zshaheen** [comment]
set `type` to `int` or `float`

**Comment by chengzhuzhang** [comment]
Refined horizontal slicing algorithm (https://github.com/zshaheen/acme-diags/commit/5eaddce1409bdc282265c8190a8dc828533be08d). The early issue dealing with missing values (MERRA reanalysis)." resolved.
