### ISSUE TITLE
Configuration file for multiple plots

### ISSUE THREAD

**Issue by golaz** [zshaheen/acme-diags#9]
Need the ability to generate a suite of plots from a single invocation of the diagnostics. We don't want the plot specifications as part of the standard parameter file since there will often be many (10s-100s) plots. So we need a separate file.

A conceptual idea of what such a configuration file might look like is attached: [plots.xml](https://github.com/zshaheen/acme-diags/files/736223/plots.xml.txt). Note that the plot configuration file would typically contain a series of plots and datasets, rather than a single one in this example.

**Comment by chengzhuzhang** [comment]
Solved in the branch merge: Multiple runs test #14 (https://github.com/zshaheen/acme-diags/pull/14)
